apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
spec:
  type: NodePort
  selector:
    app: node-web-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30036  # Accessible via localhost:30036